print('Tabuada')
t = int(input('Digite o numero da tabuada que gostaria de ver : '))
print(' 1 = {}'.format(t*1))
print(' 2 = {}'.format(t*2))
print(' 3 = {}'.format(t*3))
print(' 4 = {}'.format(t*4))
print(' 5 = {}'.format(t*5))
print(' 6 = {}'.format(t*6))
print(' 7 = {}'.format(t*7))
print(' 8 = {}'.format(t*8))
print(' 9 = {}'.format(t*9))
print('10 = {}'.format(t*10))
